apiVersion: v1
kind: Pod
metadata:
  name: multiple-containers
spec:
  containers:
  - name: multiple-containers-container-1
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo cont1 > index.html && python -m http.server 8082']
  - name: multple-containers-container-1
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo cont1 > index.html && python -m http.server 8083']